### ISSUE TITLE
using AutoIt Tool to upload profile pic

### ISSUE THREAD

**Issue by Maheshwaridec15** [tabhresh/Edureka_15thDec#13]
Hi ABhresh,
I tried to use AutoIt tool to upload the profile pic in my Edureka portal.
The script executed without error, but when I looked into the portal, it was not reflected.
I mean the pic did not appear on the profile.

**Comment by Maheshwaridec15** [comment]
@Test (priority =1)
    public void myProfile() throws IOException, InterruptedException  {
		
			//try {
				driver.findElement(By.xpath("//*[@id=\"header-II\"]/section/nav/div/ul[2]/li[1]/a/span")).click();
				
				//editing personal details
				driver.findElement(By.linkText("My Profile")).click();
				driver.findElement(By.xpath("//*[@id=\"personal_details\"]/i")).click();
				driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
				driver.findElement(By.xpath("//*[@id=\"collapseOne\"]/div/div/div[2]/a/i")).click();
				//upload profile photo
				driver.findElement(By.id("custom-input")).click();
				Thread.sleep(5000);
				Runtime.getRuntime().exec("F:\\edurekha\\AutoIt\\Edureka_profilephoto.exe");
				Thread.sleep(1000);
				driver.findElement(By.xpath("//*[@id=\"onboarding\"]/div/div[1]/div[2]/div[2]/app-onboarding-personal-details/div[2]/div/div/div[2]/div[2]/button")).click();
				System.out.println("File Uploaded Successfully");
				
				driver.findElement(By.name("fullname")).clear();
				driver.findElement(By.name("fullname")).sendKeys("Maheshwari Thiyagarajan");

				WebDriverWait wait = new WebDriverWait(driver, 5);
				WebElement e = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//*[@class='btn btn-default pull-right verify-continue-btn' and @type='button']")));
				WebElement mouseHover = driver
						.findElement(By.xpath("//*[@class='btn btn-default pull-right verify-continue-btn' and @type='button']"));
				Actions act = new Actions(driver);
				act.moveToElement(mouseHover).click().build().perform();
			
    }

**Comment by Maheshwaridec15** [comment]
output i get is:
File Uploaded Successfully
Closing the browser....
PASSED: ReadData
PASSED: myProfile
PASSED: logoutAUT

===============================================
    Default test
    Tests run: 3, Failures: 0, Skips: 0
===============================================
===============================================
Default suite
Total tests run: 3, Failures: 0, Skips: 0
===============================================

**Comment by tabhresh** [comment]
Hi,
Pls share the code as it is and complete code.
this is half part where even "@test" annotation is written in small letter which will not work and there might be some other things to which may have an impact on the execution part. So full code is needed and preferable with password of your account as I dont have a User account to test your code

**Comment by Maheshwaridec15** [comment]
[module11.zip](https://github.com/tabhresh/Edureka_15thDec/files/2794879/module11.zip)

**Comment by Maheshwaridec15** [comment]
@test is proper in code..dunno how while copying some error have occured..

**Comment by tabhresh** [comment]
Many mistakes in the script:
Autoit script not correct>> the locator was incorrect in the .au3 script so script was not working
Using Webdriver wait but not implementing it is of no use -WebElement created but no action used for example "e.click" here in your script reader will not unnderstand why you have created 'e'?
Unnecessary usage of Actions Commands.
Also one more suggestion - write the comments more to make it easy for the reader.


Many flaws I have noticed in your script and I feel you need more of practice rather than just trying to complete the assignments and try to focus on each topics well and learn them first then move to next. clubbing multiple topics without the need is going to make the script complex. So please start with basic examples for each topic and then go ahead with solving assignments and project.
