### ISSUE TITLE
Contains xPath is not returning any web elements

### ISSUE THREAD

**Issue by asad-ahml** [tabhresh/Edureka_15thDec#3]
**By MA**

Hi, I am trying to create a xpath for a title on https://www.linkedin.com/. The title is "Find a colleague". I have created following xpath, but it is not picking any web element.

//*[contains(@text, ‘Find a colleague‘)]

Wondering what I am missing?
![image](https://user-images.githubusercontent.com/46060060/50530958-fe1b3680-0ab7-11e9-9c5c-80ed532e1c95.png)

**Comment by tabhresh** [comment]
Expected: //*[contains(**text()**, ‘Find a colleague‘)]   -- here when using text attribute we dont use @ we directly use text().
Actual: //*[contains(@text, ‘Find a colleague‘)]

Also it is Just a Text not Title because in selenium we capture title which means Page title... terminology difference :-)

**Comment by asad-ahml** [comment]
Trying to push code to repository but keep getting this error message

![image](https://user-images.githubusercontent.com/46060060/50618375-2683a600-0ea7-11e9-9c04-5d8846ee98c7.png)

**Comment by tabhresh** [comment]
Are u trying to push to my project?
if yes then not allowed!
If its related to push to your own repository then there could be many reasons for it which needs to be looked upon try requesting Support team for the issue Git expert will help you.
