### ISSUE TITLE
Taskno 3 and 4 of this Travelbooking program is not working

### ISSUE THREAD

**Issue by Maheshwaridec15** [tabhresh/Edureka_15thDec#5]
[travelbooking program.docx](https://github.com/tabhresh/Edureka_15thDec/files/2717015/travelbooking.program.docx)

**Comment by Maheshwaridec15** [comment]
Though the xpath values are unique, it throws element not found, or mouse house location unspecified.
Not sure what is missed. Please show some lights on this.

**Comment by tabhresh** [comment]
1) You need more practice of the concepts!
2) Always focus when I am teaching because, I give many points during explanation which are helpful.
3) Xpath needs to be customized when needed specially with dynamic elements
4) Lot of usage of Unnecessary waits and Not allowed to use Thread.sleep (already instructed during the session)
5) Analysis of which techniques are suitable for which element is very important.
6) Using Actions Class requires you to use ".build()" and ".perform()" methods too.

`package module5;

import java.util.concurrent.TimeUnit;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

public class GOIBIBO {
	public static void main(String[] args) throws InterruptedException {
		// Open Browser
		System.setProperty("webdriver.chrome.driver", "E:\\Abhresh\\Installation_stuff\\ExeFiles\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();

		driver.manage().deleteAllCookies();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		driver.manage().timeouts().pageLoadTimeout(30, TimeUnit.SECONDS);
		
		// Open AUT
		driver.get("https://www.goindigo.in");
		
		// Task:1 Getting the current window name
		String CW = driver.getWindowHandle();
		System.out.println("Main window name is:" + CW);
		System.out.println("------------------------");

		// Task:2 Click on onewaytrip
		driver.findElement(By.xpath("//*[@id='oneWayTrip']")).click();
		
		// Task:3 Getting the Departure Destination Details
		driver.findElement(By.name("or-src")).click();
		driver.findElement(By.name("or-src")).sendKeys("Bengaluru");
		WebElement mouseHover = driver
				.findElement(By.xpath("//*[@data-name='Bengaluru' and @data-iata='BLR']"));
		Actions act = new Actions(driver);
		act.moveToElement(mouseHover).click().build().perform();

		// Task:4 Getting the Arrival Destination details
		driver.findElement(By.name("or-dest")).click();
		driver.findElement(By.name("or-dest")).sendKeys("Lucknow");
		driver.findElement(By.xpath("//*[@data-name='Lucknow' and @data-iata='LKO']")).click();
		
		//Departure Dates
		driver.findElement(By.xpath("//*[@id='oneWayTrip']")).click();
				
		// Task:5 Passenger details
		driver.findElement(By.name("passenger")).click();
		
		// book for three adults
		driver.findElement(By.xpath("//*[@name='passenger']//following::button[2]")).click();
		driver.findElement(By.xpath("//*[@name='passenger']//following::button[2]")).click();
		
		// book for two children
		driver.findElement(By.xpath("//*[@name='passenger']//following::button[4]")).click();
		driver.findElement(By.xpath("//*[@name='passenger']//following::button[4]")).click();
		
		// click on submit/done
		WebElement Done = driver.findElement(By.xpath("//button[@class='btn btn-primary pax-done']"));
		act.moveToElement(Done).click().build().perform();
	}}`

**Comment by Maheshwaridec15** [comment]
Yes.
Done.
